[localhost]
127.0.0.1 ansible_connection=local

[all:vars]
# Define our target static IPs so they are easily referenceable
NETWORK_NAME=banking-network
SUBNET=192.168.1.0/24

IP_APACHE=192.168.1.1
IP_GATEWAY_1=192.168.1.2
IP_GATEWAY_2=192.168.1.3
IP_MICROSERVICE_1=192.168.1.4
IP_MICROSERVICE_2=192.168.1.5
IP_MICROSERVICE_3=192.168.1.6
IP_REDIS=192.168.1.7